# SPDX-License-Identifier: MPL-2.0
# Pack package manager configuration for idris2-cno
# See: https://github.com/stefan-hoeck/idris2-pack

[custom.all.idris2-cno]
type   = "local"
path   = "."
ipkg   = "idris2-cno.ipkg"

# For pack-db registration, add to collections/HEAD.toml:
# [db.idris2-cno]
# type   = "github"
# url    = "https://github.com/hyperpolymath/idris2-cno"
# commit = "main"
# ipkg   = "idris2-cno.ipkg"
